### PR TITLE
Publication date field indexed using solr date type

### PR DESCRIPTION
**Pull request by JacobR**
Should be good to go.

### CODE REVIEW

**Comment by ebenenglish** [comment]
This is looking pretty good, a couple comments:

1. We should allow dates in the form of `YYYY`, `YYYY-MM`, or `YYYY-MM-DD`.

2. The changes in this PR have introduced a number of new Rubocop offenses, run `rubocop` from the project home directory to see a full list. (Some of these existed previously, so not every offense needs to be addressed, but if you can try and fix as many of the ones that are related to the new changes as possible, that would be great.)

**Comment by JacobR** [comment]
This looks like it may be a bit more complicated than it appears. With Solr date objects, the time component looks to be optional and will be filled out by Solr with (i.e. entering a  `publication_date_start` to 2016-05-05 will produce `"publication_date_start_dtsim":["2016-05-05T00:00:00Z"]`. However, there is no contingency with regards to years or year/month combinations.

It looks like, in order to do this, we'll need to take advantage of Solr's _DateRangeField_, which supports single dates but expands to allow ranges. This requires a bit more tweaks to the solrizer gem, but I'd like to discuss this before making major updates. As we discussed, the Solrizer gem isn't being used the same way now. I'm not sure how this changes development, as the documentation is sparse.

**Comment by ebenenglish** [comment]
Can we work on reducing the number of Rubocop offenses? Most of the ones that have been introduced by these commits should be pretty easy to fix, I think.

**Comment by ebenenglish** [comment]
Doing some testing, I noticed this issue:

As an admin user
When I am on the 'Add New' form for Article or Issue
And I enter a date in the 'Publication Date' field and click Save
The publication date is stored correctly in Fedora and Solr
But when I click the 'Edit' button for that work
The previously saved publication date is missing

**Comment by ebenenglish** [comment]
Also, I wonder if it might be possible to DRY some of the indexing/validation stuff?

1. **date range indexing**
Both `NewspaperTitleIndexer` and `NewspaperContainerIndexer` have (basically) the same code for the date range indexing. We could possibly combine these into a single method in `NewspaperWorks::NewspaperCoreIndexer` that can be called from `NewspaperTitleIndexer` and `NewspaperContainerIndexer`?

2. **publication_date_valid**
This method is repeated in both `NewspaperArticle` and `NewspaperIssue`. We could possibly create something like `NewspaperWorks::PublicationDateValidator` in `app/validators/newspaper_works/publication_date_validator.rb` that would then get included in the models? (See Hyrax [HasOneTitleValidator](https://github.com/samvera/hyrax/blob/master/app/validators/hyrax/has_one_title_validator.rb) for an example.)

3. **publication_date_start_valid, publication_date_end_valid, publication_date_start_before_publication_date_end**
These 3 methods are duplicated in `NewspaperTitle` and `NewspaperContainer`. Could possibly pursue validator pattern described above?

**Pull request merged**
