### PR TITLE
Update calendar view to clearfix properly

### PR DESCRIPTION
**Pull request by JacobR**
This is looking better.

### CODE REVIEW

**Comment by ebenenglish** [comment]
This seems better. Works well at different sizes as well.

Do we want to address items 2 and 3 from #138 as part of the PR? Or just limit it to item 1 for now?

**Comment by JacobR** [comment]
For sure. I should be able to get that rolled in.

**Comment by JacobR** [comment]
I've updated the branch to include the updates we've discussed.

**Comment by ebenenglish** [comment]
@JacobR This looks pretty good at the moment, nice work! A couple comments:
* I like the year-selection drop-down. Can we make the font size smaller perhaps? My concern would be that a longer list of years could get pretty unwieldy at that size.
* Could we add a bit of padding/margin to the bottom of the `#issues_calendar` div? Just need a bit more separation between the calendar and the metadata.

**Comment by ebenenglish** [comment]
Build passed for latest commit for Rails 5.1.7, timed out for 5.0.7. Think this is OK to merge.

**Pull request merged**
